name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run ci suite
        run: make ci
