name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run reviewdog
        run: |
          cat testcases/tflint/simple/sarif.json | ./sarif-to-rdjson
            | reviewdog -f rdjson --filter-mode nofilter --reporter github-pr-check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
